# Generated by Django 3.0.4 on 2020-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descr',
            field=models.TextField(max_length=20),
        ),
    ]
