# Generated by Django 3.0.4 on 2020-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200804_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descr',
            field=models.TextField(max_length=5000),
        ),
    ]
