# Generated by Django 3.0.4 on 2020-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200804_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
