# Generated by Django 3.0.4 on 2020-10-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicio_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Apellidos',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Cedula',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
