# Generated by Django 3.0.4 on 2020-10-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201001_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Correo_electronico',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
